### ISSUE TITLE
XLNetTokenizer and BertExpressionTokenizer

### ISSUE THREAD

**Issue by pjuangph** [IBM/regression-transformer#10]
1. I see you guys have 2 tokenizers, Bert and XLNET. How are you using the two tokenizers? 
2. Can you give more detail on how you go from the vocab to training in the readme file?

**Comment by jannisborn** [comment]
Hi @pjuangph,

Thanks for the interest.

1. Even though our backbone is XLNet, we use a tokenizer class that inherits from the BERT tokenizer (called `ExpressionBertTokenizer`). That's not problematic, because we dont finetune XLNet, we train it entirely from scratch on molecules (original XLNet was only trained on natural text). So, generally we use this `ExpressionBertTokenizer` for modeling small molecules, proteins and chemical reactions. But we have one application on a NLP dataset. For that one dataset, we finetune the original XLNet model and hence wrote this `XLNetRTTokenizer` which inherits from the `XLNetTokenizer`.
2. Not super sure about this, can you ask more specifically maybe? The README describes how to launch a training so it's covered in principle. Do you need intuition about the parameters to set? 

Hope this helps

**Comment by jannisborn** [comment]
Closing this, feel free to reopen if applicable
