### ISSUE TITLE
Replicating Chemical Reaction Modelling Results

### ISSUE THREAD

**Issue by Peggy-Li** [IBM/regression-transformer#21]
Hi,

I would like to replicate your results on the chemical reaction problem on the Buchwald Hartwig dataset. Should I be using the main branch, or eval_gt4sd_trained, or gt4sd? 

I'm guessing I should set "entity_to_mask" to values between 0 and 5 (one for each precursor type), and run the eval_language_modeling script for each of those. But, I end up getting this error on the main branch:

```
  File ".../regression-transformer/terminator/collators.py", line 130, in find_entity_indices
    num_entities = int((inputs == self.entity_separator_idx).sum(axis=1).min()) + 1
AttributeError: 'ConditionalGenerationEvaluationCollator' object has no attribute 'entity_separator_idx'
```

Also, does my parameter file look correct?

```
{
    "property_tokens": [
        "<yield>"
    ],
    "property_tokens_to_mask": [
           5
    ],
    "line_by_line": true,
    "beam_width": 3,
    "entity_to_mask": 0,

    "plm_probability": 1.0,
    "max_span_length": 7
}
```

Thank you.

**Comment by jannisborn** [comment]
Hi @Peggy-Li,

Thanks for the interest in our work. Since your error is at inference time, I assume that you already finetuned a model on BH data, starting from USPTO checkpoint. Note that note that finetuning the RT will almost always yield better results than starting from scratch. We open-sourced the USPTO checkpoint but not the BH one.

Did you train/finetune via GT4SD or via the instructions in the README of this repo?

**Comment by Peggy-Li** [comment]
I trained with the instructions in the readme, since I want to test out
modifications to RT.

I actually ran the inference on a from-scratch model, but I've since found
the pretrained USPTO model and will run with that. But my hunch is that
error would remain.

**Comment by jannisborn** [comment]
The short answer is that you will need to specify the entity separator in the config file. Otherwise the attribute is not set, hence you get the error:

```json
{
"entity_separator_token": ".",
}
```

This should fix your issue.

===
In general, I recommend to use the RT trainer available via GT4SD:
- Install GT4SD: https://github.com/gt4sd/gt4sd-core
- Launch the RT trainer (see [here](https://github.com/GT4SD/gt4sd-core/tree/main/examples/regression_transformer) for instructions). Start from the USPTO model and finetune on the BH data
- After the finetuning is complete, go to the `regression-transformer` repo, do a `git checkout eval_gt4sd_trained` to check out the correct branch.
- Then run your evaluation as you did above

**Comment by Peggy-Li** [comment]
That fixed it. Thanks!

I have a second question, how do you evaluate the conditional generation given the sample's original yield value? From my understanding, the evaluation will do conditional generation for primer yield values from the "conditioning range", not the original yield.

**Comment by jannisborn** [comment]
Great to hear!

Your understanding is correct, that is the purpose of `ConditionalGenerationEvaluationCollator`. 
To evaluate on the original yield, you can use `ConditionalGenerationTrainCollator` which was intended for training purposes only. This will keep the original yield and not impute with desired, hypothetical yields

**Comment by Peggy-Li** [comment]
Hi Jannis,

Thanks for you previous assistance! Could you give me a few more pointers on replicating the reaction results? I'm still having some trouble with it, where at the very least I'm not getting good yield predictions, getting an R2 much lower (0.2) than your 0.939 on the Buchwald-Hartwig data. This is from the pretrained USPTO model from the Box link.

I am not using the GT4SD trainer, since I thought it would make it easier to make modifications to RT. I'm using code from the main branch. So main question, do you think that is the biggest problem? Are there edits to the RT code in GT4SD that could account for this difference, or is it more likely user error?

Beyond that, even if using GT4SD would be the fix, I have a few more questions:

1. For the BH data, did you use the augmented training data (from Box)? If so, is the Suzuki coupling data supposed to have an augmented data file?
2. Is the GT4SD pretrained model different than the USPTO pretrained model in Box, and does it uses selfies? The vocab file in the Box pretrained USPTO model seems to indicate SMILES, while the BH data is SELFIES.
3. Was the GT4SD trainer what was used for the paper results? 
4. Are the particular config, training config, and vocab file used for the training/fine-tuning the reaction model available? Kind of related to the second item, in that Idk if the Box files were what produced the paper results. 

Thanks again!

**Comment by jannisborn** [comment]
You can use the GT4SD trainer and still make modifications to the RT, your env will just run the `gt4sd` branch of this repo rather than the `main` branch. As I said, `gt4sd` branch is recommended for all training & finetuning procedures. 

Regarding augmentation I think I used augmented data for BH but non-augmented for the suzuki couplings

Regarding USPTO models, I pretrained two separate ones, one on SMILES and one on SELFIES. The open-sourced one is the SMILES one but the one that was used for finetuning on BH and Suzuki couplings was the SELFIES one. This likely is a major reason for the lower performance you see

No, the GT4SD trainer was developed afterwards / concurrently to the production of the paper results

Those configs and pretrained models that are available you can find them linked in the README of the repo. There are more than 10 model checkpoints available

Hope this helps!

**Comment by Peggy-Li** [comment]
> The open-sourced one is the SMILES one but the one that was used for finetuning on BH and Suzuki couplings was the SELFIES one. This likely is a major reason for the lower performance you see

Btw, I had changed the BH data to be SMILES to match the model. Do you still expect the SMILES model to be the main cause, and that the SELFIES model is way better in general?

For the 10+ model checkpoints, are you referring to those that are shown in the HuggingFace Spaces link and I'm guessing available through gt4sd?

Thanks!

**Comment by jannisborn** [comment]
Hmmm, I think there were some issues with the SMILES reaction models this is why I had used SELFIES for finetuning on BH/SZ data after having pretrained a SELFIES as well as SMILES model on USPTO. When you convert the SELFIES to SMILES, have a look that you do it consistently with the USPTO pretraining data, i.e., either use canonical SMILES or kekulized (explicit double bonds in aromatic rings) but dont mix both notations. This should not result in such a big performance difference though.

Yes, re the checkpoints I refer to the huggingface spaces webapp. For your understanding, the HF spaces app is just a UI that runs GT4SD under the hood. IT visualizes the models exposed through GT4SD, so it's the same set of models

**Comment by Peggy-Li** [comment]
Is there a chance that the SELFIES pretrained model could be made public?

**Comment by jannisborn** [comment]
Unfortunately the checkpoint is not available anymore at this point.

What exactly are you interested in regarding the reaction models? Yield prediction? Conditional generation of precursors? 

I think the easiest could be to take the qed model (which was trained on SELFIES) and finetune this one on the USPTO data to teach general reaction chemistry. Then this model can be finetuned on BH or SZ reactions. This was the process I followed when running the experiments. USPTO finetuning was around 2-3 days whereas BH/SZ was several hours, both single-GPU

**Comment by Peggy-Li** [comment]
My main interest is in conditional generation of precursors, but I focused
on the yield prediction during debugging because I thought it would be
easier.

Interesting! I did not realize the USPTO model was fine tuned from the QED
model. Thanks for clarifying that!

**Comment by jannisborn** [comment]
Makes sense. For that application, using SELFIES rather than SMILES will be critical. I also finetuned with the following parameters:
```json
	"entity_to_mask": -1,
	"entity_separator_token": "."
```

this ensured that the training scheme was similar to the inference, so masking occurred only one on entity and entities are separated via `.`

**Comment by Peggy-Li** [comment]
What did you set the plm_probability to during finetuning? I've set it to 1, which to my understanding should mask an entire entity. That also makes training more similar to inference, but perhaps masking too much makes it hard to learn?

**Comment by jannisborn** [comment]
Yes, your understanding is correct. I set this value to 0.5 during training I believe.

The beauty of the model lies in the flexibility at inference time. You can generate full precursors but often you have some structures or motifs that you want to enforce to be present and you then provide partially corrupted sequences. It's a bit of a trade-off: Giving more flexibility to the model generally gives higher chances to obtain a sequence with desired property (see e.g., SI Figure S2 which is on protein sequences) but the model might show some mode collapse where the generated sequences are trivial or artificial (non-synthesizable). You can mitigate this by setting a lower masking probability but with less flexibility for the model you might give queries that are impossible to complete (imagine an inference query with very high desired QED where you provide a fractional molecules with a peroxide group)


Unfortunately we dont have ablation studies for the precursor generation performance as a function of masking probability but there is one on reconstructing precursors, see SI Table S5
